export const assetIndex = {
    SVG: {
        curve: '/assets/images/curve-2.svg',
        group: '/assets/svg/group.svg',
        nodejs: '/assets/svg/nodejs.svg',
        react_native: '/assets/svg/react-native.svg',
        flutter: '/assets/svg/flutter.svg',
        banner: '/assets/svg/banner.svg',
        personal: '/assets/svg/personal.svg',
        solution: '/assets/svg/solution.svg',
        quality: '/assets/svg/quality.svg',
        consult: '/assets/svg/consult.svg',
        business: '/assets/svg/business.svg',
        success: '/assets/svg/success.svg',
        python: '/assets/svg/python.svg',
        cplus: '/assets/svg/c++.svg',
        salesforce: '/assets/svg/salesforce.svg',
        adobe_commercean: '/assets/svg/adobe-commerce.svg',
        sap: '/assets/svg/sap.svg',
        powerBi: '/assets/svg/power-bi.svg',
        mongoDB: '/assets/svg/mongoDB.svg',
        amazonDB: '/assets/svg/amazonDB.svg',
        amazonShift: '/assets/svg/amazonShift.svg',
        amazonDynamo: '/assets/svg/amazonDynamo.svg',
        azureData: '/assets/svg/azureData.svg',
        azureBlob: '/assets/svg/azureBlob.svg',
        azureCosmos: '/assets/svg/azureCosmos.svg',
        apacheBase: '/assets/svg/apacheBase.svg',
        octave: '/assets/svg/octave.svg',
        r: '/assets/svg/r.svg',
        tensorFlow: '/assets/svg/tensorFlow.svg',
        opencv: '/assets/svg/opencv.svg',
        touch: '/assets/svg/touch.svg',
        spacy: '/assets/svg/spacy.svg',
        gensim: '/assets/svg/gensim.svg',
        sci: '/assets/svg/sci.svg',
        spark: '/assets/svg/spark.svg',
        k8: '/assets/svg/k8.svg',
        docker: '/assets/svg/docker.svg',
        anisble: '/assets/svg/ansible.svg',
        terraform: '/assets/svg/terraform.svg',
        packer: '/assets/svg/packer.svg',
        gitlab: '/assets/svg/gitlab.svg',
        jenkins: '/assets/svg/jenkins.svg',
        datadog: '/assets/svg/datadog.svg',
        prometheous: '/assets/svg/prometheous.svg',
        grafana: '/assets/svg/grafana.svg',
        digitalOcean: '/assets/svg/digitalOcean.svg',
        goggle: '/assets/svg/google.svg',
        aws: '/assets/svg/aws.svg',
        selenium: '/assets/svg/selenium.svg',
        appium: '/assets/svg/appium.svg',
        fmbt: '/assets/svg/fmbt.svg',
        xct: '/assets/svg/xct.svg',
        postman: '/assets/svg/postman.svg',
        vs: '/assets/svg/vs.svg'
    },
    Lottie: {
      
    },
    Gif: {
      
    },
    Image: {
      banner1: '/assets/images/banner-1.png',
      banner2: '/assets/images/banner-2.png',
      banner3: '/assets/images/banner-3.png',
      curve: '/assets/images/curve.png',
      avatar1: '/assets/images/avatar-1.png',
      avatar2: '/assets/images/avatar-2.png',
      avatar3: '/assets/images/avatar-3.png',
      avatar4: '/assets/images/avatar-4.png',
      explore1: '/assets/images/explore-1.png',
      explore2: '/assets/images/explore-2.png',
      explore3: '/assets/images/explore-3.png',
      explore4: '/assets/images/explore-4.png',
      explore5: '/assets/images/explore-5.png',
      explore6: '/assets/images/explore-6.png',
      logo: '/assets/images/logo.png',
      aboutUser: '/assets/images/about-user.png',
      value: '/assets/images/values.png',
      electron: '/assets/images/electron.png',
      laptop: '/assets/images/laptop.png',
    },
  };
  